administration/urls.py
from django.conf.urls import (
    include,
    url,
)

from . import (
    application_views,
    ban_views,
    flag_views,
    views,
)


app_name = 'administration'
application_urls = [
    url('^$', application_views.list_all_applications,
        name='list_all_applications'),
    url('^mine/$', application_views.list_participating_applications,
        name='list_participating_applications'),
    url('^social/$', application_views.list_social_applications,
        name='list_social_applications'),
    url('^content/$', application_views.list_content_applications,
        name='list_content_applications'),
    url('^create/$', application_views.create_application,
        name='create_application'),
    url('^application/(?P<application_id>\d+)/$',
        application_views.view_application,
        name='view_application'),
    url('^application/(?P<application_id>\d+)/claim/$',
        application_views.claim_application, name='claim_application'),
    url('^application/(?P<application_id>\d+)/resolve/$',
        application_views.resolve_application, name='resolve_application'),
]
flag_urls = [
    url('^$', flag_views.list_all_flags, name='list_all_flags'),
    url('^mine/$', flag_views.list_participating_flags,
        name='list_participating_flags'),
    url('^social/$', flag_views.list_social_flags,
        name='list_social_flags'),
    url('^content/$', flag_views.list_content_flags,
        name='list_content_flags'),
    url('^create/$', flag_views.create_flag, name='create_flag'),
    url('^flag/(?P<flag_id>\d+)/$', flag_views.view_flag,
        name='view_flag'),
    url('^flag/(?P<flag_id>\d+)/join/$',
        flag_views.join_flag, name='join_flag'),
    url('^flag/(?P<flag_id>\d+)/resolve/$',
        flag_views.resolve_flag, name='resolve_flag'),
]
ban_urls = [
    url('^$', ban_views.list_bans, name='list_bans'),
    url('^notice/(?P<ban_id>\d+)/(?P<ban_hash>.+)/$', ban_views.ban_notice,
        name='ban_notice'),
    url('^mine/$', ban_views.list_participating_bans,
        name='list_participating_bans'),
    url('^create/$', ban_views.create_ban, name='create_ban'),
    url('^ban/(?P<ban_id>\d+)/$', ban_views.view_ban,
        name='view_ban'),
    url('^ban/(?P<ban_id>\d+)/lift/$', ban_views.lift_ban, name='lift_ban'),
]
admin_urls = [
    url('^$', views.dashboard, name='dashboard'),
    url('^applications/', include(application_urls)),
    url('^flags/', include(flag_urls)),
    url('^bans/', include(ban_urls)),
]
urlpatterns = [
    url('^admin/', include(admin_urls)),
]

api/urls.py
from django.conf.urls import (
    include,
    url,
)


def empty_view(request):
    pass


app_name = 'api'
urlpatterns = [
    url('^$', empty_view, name='root.url'),
    url('^v1/', include('api.v1.urls')),
]

honeycomb/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    # Django app urls
    url(r'^_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^_admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # Honeycomb app urls
    url('^', include('administration.urls')),
    url('^', include('usermgmt.urls')),
    url('^', include('social.urls')),
    url('^', include('core.urls')),
    url('^', include('publishers.urls')),
    url('^', include('submissions.urls')),
    url('^', include('tags.urls')),
    url('^activity/', include('activitystream.urls')),
    url('^calls/', include('submitify.urls')),
    url('^api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publishers/urls.py
from django.conf.urls import (
    include,
    url,
)

from . import views


app_name = 'publishers'
news_patterns = [
    url(r'^$', views.list_news_items, name='list_news_items'),
    url(r'^page/(?P<page>\d+)/$', views.list_news_items,
        name='list_news_items'),
    url(r'^create/$', views.create_news_item, name='create_news_item'),
    url(r'^(?P<item_id>\d+)/$', views.view_news_item, name='view_news_item'),
    url(r'^(?P<item_id>\d+)/edit/$', views.edit_news_item,
        name='edit_news_item'),
    url(r'^(?P<item_id>\d+)/delete/$', views.delete_news_item,
        name='delete_news_item'),
]
publisher_patterns = [
    url(r'^$', views.view_publisher, name='view_publisher'),
    url(r'^news/', include(news_patterns)),
    url(r'^edit/$', views.edit_publisher, name='edit_publisher'),
    url(r'^delete/$', views.delete_publisher, name='delete_publisher'),
    url(r'^members/add/$', views.add_member, name='add_member'),
    url(r'^members/remove/$', views.remove_member, name='remove_member'),
    url(r'^editors/add/$', views.add_editor, name='add_editor'),
    url(r'^editors/remove/$', views.remove_editor, name='remove_editor'),
    url(r'^calls/$', views.list_calls, name='list_calls'),
    url(r'^calls/add/$', views.add_call, name='add_call'),
    url(r'^calls/remove/$', views.remove_call, name='remove_call'),
    url(r'^ownership/change/$', views.change_ownership,
        name='change_ownership'),
]
urlpatterns = [
    url(r'^publishers/$', views.list_publishers, name='list_publishers'),
    url(r'^publishers/(?P<page>\d+)/$', views.list_publishers,
        name='list_publishers'),
    url(r'^publishers/create/$', views.create_publisher,
        name='create_publisher'),
    url(r'^publisher/(?P<publisher_slug>[-_\w]+)/',
        include(publisher_patterns)),
]

usermgmt/urls.py
from django.conf.urls import (
    include,
    url,
)

from . import (
    group_views,
    views,
)

app_name = 'usermgmt'
group_urls = [
    url('^$', group_views.list_groups, name='list_groups'),
    url('^create/$', group_views.create_group, name='create_group'),
    url('^(?P<group_id>\d+)/$', group_views.view_group, name='view_group'),
    url('^(?P<group_id>\d+)/edit/$', group_views.edit_group,
        name='edit_group'),
    url('^(?P<group_id>\d+)/delete/$', group_views.delete_group,
        name='delete_group'),
]
urlpatterns = [
    url('^register/$', views.Register.as_view(), name='register'),
    url('^accounts/profile/$', views.update_profile, name='update_profile'),
    url('^~([^/]+)/$', views.view_profile, name='view_profile'),
    url('^~(?P<username>[^/]+)/groups/', include(group_urls)),
]

publishers/models.py
from __future__ import unicode_literals
import markdown
from PIL import Image

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils.html import strip_tags
from submitify.models import Call

from administration.models import Flag
from honeycomb_markdown import HoneycombMarkdown


def _upload_path(instance, filename, upload_type):
    return 'uploads/publisher-{}/{}'.format(
        instance.slug,
        '{}-{}.{}'.format(
            timezone.now().strftime('%Y-%m-%d-%H%M%S'),
            upload_type,
            filename.split('.')[-1]))


def logo_path(instance, filename):
    return _upload_path(instance, filename, 'logo')


def banner_path(instance, filename):
    return _upload_path(instance, filename, 'banner')


def newsitem_path(instance, filename):
    return _upload_path(instance.publisher, filename, 'newsitem')


class Publisher(models.Model):
    """A page on the site representing a publisher, collecting submissions by
    site members who are employed by or contracted under that publisher.
    """
    # The name and slug of the page
    name = models.CharField(max_length=100, help_text='''
    The name of the publisher. This will be used to create the URL.''')
    slug = models.SlugField(max_length=100, unique=True)

    # The publisher's URL
    url = models.URLField(max_length=1024, help_text='''
    The url for the publisher's homepage.''')

    # The page content
    logo = models.ImageField(upload_to=logo_path, help_text='''
    A logo image for the publisher. Aim for something close to square. This
    will be displayed in the publisher listing as well as on the publisher
    page.''')
    banner = models.ImageField(blank=True, upload_to=banner_path, help_text='''
    A banner image to display at the top of the publisher page.''')
    body_raw = models.TextField(verbose_name='body', help_text='''
    A description of the publisher; this will be the main page of the publisher
    on this site.''')
    body_rendered = models.TextField()

    # The page owner
    owner = models.ForeignKey(User, blank=True, null=True,
                              related_name='owned_publishers')

    # Users who have an editorial role with the publisher
    editors = models.ManyToManyField(User, related_name='publishers_editor_of')

    # Users who have been published by the publisher
    members = models.ManyToManyField(User, related_name='publishers_member_of')

    # Any calls for submissions run by the publisher
    calls = models.ManyToManyField(Call)

    flags = GenericRelation(Flag)

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.body_rendered = markdown.markdown(
            strip_tags(self.body_raw),
            extensions=[
                HoneycombMarkdown(),
                'pymdownx.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.smarty',
                'pymdownx.headeranchor',
                'pymdownx.magiclink',
                'pymdownx.smartsymbols',
                'pymdownx.tilde',
                'pymdownx.mark',
            ])

        super(Publisher, self).save(*args, **kwargs)

        # Resize images
        if self.logo:
            logo = Image.open(self.logo)
            logo.thumbnail((500, 500), Image.ANTIALIAS)
            logo.save(self.logo.path)
        if self.banner:
            banner = Image.open(self.banner)
            banner.thumbnail((2048, 2048), Image.ANTIALIAS)
            banner.save(self.banner.path)

    def get_absolute_url(self):
        return reverse('publishers:view_publisher', kwargs={
            'publisher_slug': self.slug,
        })


class NewsItem(models.Model):
    """An item of news from the publisher on their page."""
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    owner = models.ForeignKey(User)
    ctime = models.DateTimeField(auto_now_add=True)
    mtime = models.DateTimeField(auto_now=True)
    image = models.ImageField(blank=True, upload_to=newsitem_path)
    subject = models.CharField(max_length=200)
    body_raw = models.TextField(verbose_name='body')
    body_rendered = models.TextField()

    class Meta:
        ordering = ['-ctime']

    def save(self, *args, **kwargs):
        self.body_rendered = markdown.markdown(
            strip_tags(self.body_raw),
            extensions=[
                HoneycombMarkdown(),
                'pymdownx.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.smarty',
                'pymdownx.headeranchor',
                'pymdownx.magiclink',
                'pymdownx.smartsymbols',
                'pymdownx.tilde',
                'pymdownx.mark',
            ])

        super(NewsItem, self).save(*args, **kwargs)

        if self.image:
            image = Image.open(self.image)
            image.thumbnail((2048, 2048), Image.ANTIALIAS)
            image.save(self.image.path)

    def get_absolute_url(self):
        return reverse('publishers:view_news_item', kwargs={
            'publisher_slug': self.publisher.slug,
            'item_id': self.id,
        })

publishers/forms.py
from django import forms

from .models import (
    NewsItem,
    Publisher,
)


class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = [
            'name',
            'url',
            'logo',
            'banner',
            'body_raw',
        ]


class NewsItemForm(forms.ModelForm):
    class Meta:
        model = NewsItem
        fields = [
            'image',
            'subject',
            'body_raw',
        ]

publishers/templates/change_publisher_ownership.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <p>Change the owner of this publisher? The old owner will become an editor and can then be removed if desired.</p>
        <form method="post">
            {% csrf_token %}
            <label for="id_new_owner">Change owner to:</label>
            <div class="user_suggest">
                Username: <input type="text" name="username" id="id_new_owner" />
                <ul class="suggestions empty"></ul>
            </div>
            <button type="submit" class="btn btn-primary">Change publisher ownership</button>
        </form>
    </div>
</div>
{% endblock %}

publishers/templates/confirm_delete_newsitem.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-danger">
            You are about to delete this news item.  Are you sure you want to do this?
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    <span class="glyphicon glyphicon-remove"></span>
                    Delete news item
                </button>
                <a href="{{ news_item.get_absolute_url }}">No, take me back</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

publishers/templates/edit_news_item.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "registration/form-snippet.html" with form=form %}
            <button type="submit" class="btn btn-primary">{{ title }}</button>
        </form>
    </div>
</div>
{% endblock %}

publishers/templates/list_news_items.html
{% extends 'base.html' %}

{% block content %}
{% include 'publisher-tabs-snippet.html' %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% if user == publisher.owner %}
            <p class="text-right">
                <a href="{% url 'publishers:create_news_item' publisher_slug=publisher.slug %}" class="btn btn-primary" role="button">
                    <span class="glyphicon glyphicon-plus"></span>
                    Create a new news item
                </a>
            </p>
        {% endif %}
        {% for item in news_items %}
            <div class="news-item panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ item.subject }}</h3>
                </div>
                <div class="panel-body">
                    {% if item.image %}
                        <img class="banner" src="{{ MEDIA_ROOT }}{{ item.image.url }}" />
                    {% endif %}
                    {{ item.body_rendered|safe }}
                </div>
                <div class="panel-footer">
                    <a href="{{ item.get_absolute_url }}">View news item</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% if news_items.has_next or news_items.has_previous %}
    <div class="row">
        <div class="col-md-12 text-center">
            <nav aria-label="Publisher pages">
                <ul class="pagination">
                    {% if news_items.has_previous %}
                        <li>
                            <a href="{% url 'publishers:list_news_items' publisher_slug=publisher.slug page=news_items.previous_page_number %}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span aria-hidden="true">&laquo;</span></li>
                    {% endif %}
                    {% for page in news_items.paginator.page_range %}
                        {% if news_items.number == page %}
                            <li class="active"><a href="{% url 'publishers:list_news_items' publisher_slug=publisher.slug page=page %}">{{ page }} <span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li><a href="{% url 'publishers:list_news_items' publisher_slug=publisher.slug page=page %}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if news_items.has_next %}
                        <li>
                            <a href="{% url 'publishers:list_news_items' publisher_slug=publisher.slug page=news_items.next_page_number %}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span aria-hidden="true">&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}
{% endblock %}

publishers/templates/list_publishers.html
{% extends 'base.html' %}
{% load excerpts %}

{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% if user.is_authenticated %}
            <p class="text-right">
                {% if perms.publishers.add_publisher %}
                    <a class="btn btn-primary" role="button" href="{% url 'publishers:create_publisher' %}">
                        <span class="glyphicon glyphicon-plus"></span>
                        Create publisher
                    </a>
                {% else %}
                    Don't see your publisher here? <a href="{% url 'administration:create_application' %}">Apply to create a publisher page</a>
                {% endif %}
            </p>
        {% endif %}
        {% for publisher in publishers %}
            <div class="publisher-listing clearfix">
                <a href="{{ publisher.get_absolute_url }}">
                    <img class="logo" src="{{ MEDIA_ROOT }}{{ publisher.logo.url }}" />
                    <h2>{{ publisher.name }}</h2>
                </a>
                <div class="body">
                    {{ publisher.body_rendered|get_first_paragraphs|safe }}
                </div>
                <div class="foot">
                    <a href="{{ publisher.get_absolute_url }}">Visit {{ publisher.name }}'s publisher page</a>
                </div>
            </div>
        {% empty %}
            <em>No publishers to list!</em>
        {% endfor %}
    </div>
</div>
{% if publishers.has_next or publishers.has_previous %}
    <div class="row">
        <div class="col-md-12 text-center">
            <nav aria-label="Publisher pages">
                <ul class="pagination">
                    {% if publishers.has_previous %}
                        <li>
                            <a href="{% url 'publishers:list_publishers' page=publishers.previous_page_number %}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span aria-hidden="true">&laquo;</span></li>
                    {% endif %}
                    {% for page in publishers.paginator.page_range %}
                        {% if publishers.number == page %}
                            <li class="active"><a href="{% url 'publishers:list_publishers' page=page %}">{{ page }} <span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li><a href="{% url 'publishers:list_publishers' page=page %}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if publishers.has_next %}
                        <li>
                            <a href="{% url 'publishers:list_publishers' page=publishers.next_page_number %}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span aria-hidden="true">&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}
{% endblock %}

publishers/templates/publisher-tabs-snippet.html
<div class="row publisher-tabs">
    <ul class="nav nav-tabs">
        <li role="presentation"{% if tab == 'home' %} class="active"{% endif %}>
            <a href="{{ publisher.get_absolute_url }}">Home</a>
        </li>
        <li role="presentation"{% if tab == 'news' %} class="active"{% endif %}>
            <a href="{% url 'publishers:list_news_items' publisher_slug=publisher.slug %}">News</a>
        </li>
        {% if tab == 'calls' or user == publisher.owner or publisher.calls.count > 0 %}
            <li role="presentation"{% if tab == 'calls' %} class="active"{% endif %}>
                <a href="{% url 'publishers:list_calls' publisher_slug=publisher.slug %}">Calls for submissions</a>
            </li>
        {% endif %}
    </ul>
</div>

publishers/templates/view_news_item.html
{% extends 'base.html' %}

{% block content %}
{% include 'publisher-tabs-snippet.html' %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% if user == publisher.owner %}
            <p class="text-right">
                <a href="{% url 'publishers:edit_news_item' publisher_slug=publisher.slug item_id=news_item.id %}" class="btn btn-primary" role="button">
                    <span class="glyphicon glyphicon-edit"></span>
                    Edit news item
                </a>
                <a href="{% url 'publishers:delete_news_item' publisher_slug=publisher.slug item_id=news_item.id}" class="btn btn-danger" role="button">
                    <span class="glyphicon glyphicon-remove"></span>
                    Delete news item
                </a>
            </p>
        {% endif %}
        <h2>{{ news_item.subject }}</h2>
        {% if news_item.image %}
            <img class="banner" src="{{ MEDIA_ROOT }}{{ news_item.image.url }}" />
        {% endif %}
        {{ news_item.body_rendered|safe }}
    </div>
</div>
{% endblock %}

publishers/templates/view_publisher.html
{% extends 'base.html' %}
{% load gravatar %}
{% load campaignify %}

{% block content %}
{% include 'publisher-tabs-snippet.html' %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% if publisher.banner %}
            <img class="banner" src="{{ MEDIA_ROOT }}{{ publisher.banner.url }}" />
        {% endif %}
        <div class="panel panel-default submission-details">
            <div class="panel-body">
                <img src="{{ MEDIA_ROOT }}{{ publisher.logo.url }}" class="submission-icon" />
                <dl class="dl-indent">
                    <dt>Website</dt>
                    <dd><a href="{{ publisher.url|campaignify:'direct link,publisher page' }}">{{ publisher.url }}</a></dd>
                    <dt>Owner</dt>
                    <dd>
                        {% if publisher.owner %}
                            <a href="{% url 'usermgmt:view_profile' publisher.owner.username %}">
                                {{ publisher.owner.email|gravatar:'40' }}
                                {{ publisher.owner.profile.get_display_name }}
                            </a>
                        {% else %}
                            <em>Not claimed</em>
                        {% endif %}
                        {% if perms.publishers.add_publisher %}
                            <div class="show-form">
                                <em>Change</em> <span class="caret"></span><input type="checkbox" />
                                <form class="ownership-form panel panel-default" method="post" action="{% url 'publishers:change_ownership' publisher_slug=publisher.slug %}">
                                    {% csrf_token %}
                                    <div class="panel-body">
                                        <label for="id_new_owner">Change owner to:</label>
                                        <div class="user_suggest">
                                            Username: <input type="text" name="username" id="id_new_owner" />
                                            <ul class="suggestions empty"></ul>
                                        </div>
                                        <button type="submit" class="btn btn-default btn-xs">Change ownership</button>
                                    </div>
                                </form>
                            </div>
                        {% endif %}
                    </dd>
                    <dt>Editors</dt>
                    <dd>
                        <ul>
                            {% for editor in publisher.editors.all %}
                                <li class="clearfix">
                                    <a href="{% url 'usermgmt:view_profile' editor.username %}" class="pull-left">
                                        {{ editor.email|gravatar:'40' }}
                                        {{ editor.profile.get_display_name }}
                                    </a>
                                    {% if user == publisher.owner %}
                                        <form method="post" action="{% url 'publishers:remove_editor' publisher_slug=publisher.slug %}" class="pull-right">
                                            {% csrf_token %}
                                            <input type="hidden" name="username" value="{{ editor.username }}" />
                                            <button class="btn btn-danger btn-xs" type="submit">
                                                <span class="glyphicon glyphicon-remove"></span>
                                            </button>
                                        </form>
                                    {% endif %}
                                </li>
                            {% empty %}
                                <li><em>No additional editors</em></li>
                            {% endfor %}
                            {% if user == publisher.owner %}
                                <div class="show-form">
                                    <em>Add</em> <span class="caret"></span><input type="checkbox" />
                                    <form class="ownership-form panel panel-default" method="post" action="{% url 'publishers:add_editor' publisher_slug=publisher.slug %}">
                                        {% csrf_token %}
                                        <div class="panel-body">
                                            <label for="id_new_editor">Add editor:</label>
                                            <div class="user_suggest">
                                                Username: <input type="text" name="username" id="id_new_editor" />
                                                <ul class="suggestions empty"></ul>
                                            </div>
                                            <button type="submit" class="btn btn-default btn-xs">Add editor</button>
                                        </div>
                                    </form>
                                </div>
                            {% endif %}
                        </ul>
                    </dd>
                    <dt>Writers</dt>
                    <dd>
                        <ul>
                            {% for member in publisher.members.all %}
                                <li class="clearfix">
                                    <a href="{% url 'usermgmt:view_profile' member.username %}" class="pull-left">
                                        {{ member.email|gravatar:'40' }}
                                        {{ member.profile.get_display_name }}
                                    </a>
                                    {% if user == publisher.owner %}
                                        <form method="post" action="{% url 'publishers:remove_member' publisher_slug=publisher.slug %}" class="pull-right">
                                            {% csrf_token %}
                                            <input type="hidden" name="username" value="{{ member.username }}" />
                                            <button class="btn btn-danger btn-xs" type="submit">
                                                <span class="glyphicon glyphicon-remove"></span>
                                            </button>
                                        </form>
                                    {% endif %}
                                </li>
                            {% empty %}
                                <li><em>No additional members</em></li>
                            {% endfor %}
                            {% if user == publisher.owner %}
                                <div class="show-form">
                                    <em>Add</em> <span class="caret"></span><input type="checkbox" />
                                    <form class="ownership-form panel panel-default" method="post" action="{% url 'publishers:add_member' publisher_slug=publisher.slug %}">
                                        {% csrf_token %}
                                        <div class="panel-body">
                                            <label for="id_new_member">Add member:</label>
                                            <div class="user_suggest">
                                                Username: <input type="text" name="username" id="id_new_member" />
                                                <ul class="suggestions empty"></ul>
                                            </div>
                                            <button type="submit" class="btn btn-default btn-xs">Add member</button>
                                        </div>
                                    </form>
                                </div>
                            {% endif %}
                        </ul>
                    </dd>
                </dl>
                <a role="button" class="btn btn-default" href="{% url 'publishers:edit_publisher' publisher_slug=publisher.slug %}">Edit publisher</a>
            </div>
        </div>
        {{ publisher.body_rendered|safe }}
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>News</h2>
        {% for item in publisher.newsitem_set.all|slice:":5" %}
            <div class="news-item panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ item.subject }}</h3>
                </div>
                <div class="panel-body">
                    {% if item.image %}
                        <img class="banner" src="{{ MEDIA_ROOT }}{{ item.image.url }}" />
                    {% endif %}
                    {{ item.body_rendered|safe }}
                </div>
                <div class="panel-footer">
                    <a href="{{ item.get_absolute_url }}">View news item</a>
                </div>
            </div>
        {% empty %}
            <p class="text-center"><em>No news to display</em></p>
        {% endfor %}
        {% if publisher.newsitem_set.count > 5 %}
            <a href="{% url 'publishers:list_news_items' publisher_slug=publisher.slug %}">More news</a>
        {% endif %}
    </div>
</div>
{% endblock %}