administration/urls.py
from django.conf.urls import (
    include,
    url,
)

from . import (
    application_views,
    ban_views,
    flag_views,
    views,
)


app_name = 'administration'
application_urls = [
    url('^$', application_views.list_all_applications,
        name='list_all_applications'),
    url('^mine/$', application_views.list_participating_applications,
        name='list_participating_applications'),
    url('^social/$', application_views.list_social_applications,
        name='list_social_applications'),
    url('^content/$', application_views.list_content_applications,
        name='list_content_applications'),
    url('^create/$', application_views.create_application,
        name='create_application'),
    url('^application/(?P<application_id>\d+)/$',
        application_views.view_application,
        name='view_application'),
    url('^application/(?P<application_id>\d+)/claim/$',
        application_views.claim_application, name='claim_application'),
    url('^application/(?P<application_id>\d+)/resolve/$',
        application_views.resolve_application, name='resolve_application'),
]
flag_urls = [
    url('^$', flag_views.list_all_flags, name='list_all_flags'),
    url('^mine/$', flag_views.list_participating_flags,
        name='list_participating_flags'),
    url('^social/$', flag_views.list_social_flags,
        name='list_social_flags'),
    url('^content/$', flag_views.list_content_flags,
        name='list_content_flags'),
    url('^create/$', flag_views.create_flag, name='create_flag'),
    url('^flag/(?P<flag_id>\d+)/$', flag_views.view_flag,
        name='view_flag'),
    url('^flag/(?P<flag_id>\d+)/join/$',
        flag_views.join_flag, name='join_flag'),
    url('^flag/(?P<flag_id>\d+)/resolve/$',
        flag_views.resolve_flag, name='resolve_flag'),
]
ban_urls = [
    url('^$', ban_views.list_bans, name='list_bans'),
    url('^notice/(?P<ban_id>\d+)/(?P<ban_hash>.+)/$', ban_views.ban_notice,
        name='ban_notice'),
    url('^mine/$', ban_views.list_participating_bans,
        name='list_participating_bans'),
    url('^create/$', ban_views.create_ban, name='create_ban'),
    url('^ban/(?P<ban_id>\d+)/$', ban_views.view_ban,
        name='view_ban'),
    url('^ban/(?P<ban_id>\d+)/lift/$', ban_views.lift_ban, name='lift_ban'),
]
admin_urls = [
    url('^$', views.dashboard, name='dashboard'),
    url('^applications/', include(application_urls)),
    url('^flags/', include(flag_urls)),
    url('^bans/', include(ban_urls)),
]
urlpatterns = [
    url('^admin/', include(admin_urls)),
]

api/urls.py
from django.conf.urls import (
    include,
    url,
)


def empty_view(request):
    pass


app_name = 'api'
urlpatterns = [
    url('^$', empty_view, name='root.url'),
    url('^v1/', include('api.v1.urls')),
]

honeycomb/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    # Django app urls
    url(r'^_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^_admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # Honeycomb app urls
    url('^', include('administration.urls')),
    url('^', include('usermgmt.urls')),
    url('^', include('social.urls')),
    url('^', include('core.urls')),
    url('^', include('publishers.urls')),
    url('^', include('submissions.urls')),
    url('^', include('tags.urls')),
    url('^activity/', include('activitystream.urls')),
    url('^calls/', include('submitify.urls')),
    url('^api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)

from . import views

app_name = 'social'
user_urls = [
    url('^watch/$', views.watch_user, name='watch_user'),
    url('^unwatch/$', views.unwatch_user, name='unwatch_user'),
    url('^block/$', views.block_user, name='block_user'),
    url('^unblock/$', views.unblock_user, name='unblock_user'),
    url('^message/$', views.message_user, name='message_user'),
]
notification_urls = [
    url('^$', views.view_notifications_ab, name='view_notifications'),
    url('^categories/$', views.view_notifications_categories,
        name='view_notifications_categories'),
    url('^timeline/$', views.view_notifications_timeline,
        name='view_notifications_timeline'),
    url('^timeline/(?P<page>\d+)/$', views.view_notifications_timeline,
        name='view_notifications_timeline'),
    url('^remove/$', views.remove_notifications, name='remove_notifications'),
    url('^nuke/$', views.nuke_notifications, name='nuke_notifications'),
]
submission_urls = [
    url('^favorite/$', views.favorite_submission, name='favorite_submission'),
    url('^unfavorite/$', views.unfavorite_submission,
        name='unfavorite_submission'),
    url('^rate/$', views.rate_submission, name='rate_submission'),
    url('^enjoy/$', views.enjoy_submission, name='enjoy_submission'),
]
comment_urls = [
    url('^post/$', views.post_comment, name='post_comment'),
    url('^delete/$', views.delete_comment, name='delete_comment'),
]

urlpatterns = [
    url('^~([^/]+)/', include(user_urls)),
    url('^notifications/', include(notification_urls)),
    url('^comment/', include(comment_urls)),
    url(settings.SUBMISSION_BASE, include(submission_urls)),
]

submissions/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)

from . import (
    folder_views,
    views,
)

app_name = 'submissions'
full_folder_patterns = [
    url('^$', folder_views.view_folder, name='view_folder'),
    url('^page/(?P<page>\d+)/', folder_views.view_folder, name='view_folder'),
    url('^edit/$', folder_views.update_folder, name='update_folder'),
    url('^delete/$', folder_views.delete_folder, name='delete_folder'),
    url('^reorder/$', folder_views.update_submission_order_in_folder,
        name='update_submission_order_in_folder'),
]
folder_patterns = [
    url('^$', folder_views.view_root_level_folders,
        name='view_root_level_folders'),
    url('^page/(?P<page>\d+)/$', folder_views.view_root_level_folders,
        name='view_root_level_folders'),
    url('^create/$', folder_views.create_folder, name='create_folder'),
    url('^(?P<folder_id>\d+)/$', folder_views.view_folder, name='view_folder'),
    url('^(?P<folder_id>\d+)-(?P<folder_slug>[-\w]+)/',
        include(full_folder_patterns))
]
submission_patterns = [
    url('^$', views.view_submission, name='view_submission'),
    url('^edit/$', views.edit_submission, name='edit_submission'),
    url('^delete/$', views.delete_submission, name='delete_submission'),
]
urlpatterns = [
    url('^submit/$', views.submit, name='submit'),
    url('^(?P<submission_id>\d+)/$', views.view_submission,
        name='view_submission'),
    url(settings.SUBMISSION_BASE, include(submission_patterns)),
    url('^~(?P<username>[^/]+)/submissions/$',
        views.list_user_submissions, name='list_user_submissions'),
    url('^~(?P<username>[^/]+)/submissions/page/(?P<page>\d+)/$',
        views.list_user_submissions, name='list_user_submissions'),
    url('^~(?P<username>[^/]+)/favorites/$',
        views.list_user_favorites, name='list_user_favorites'),
    url('^~(?P<username>[^/]+)/favorites/page/(?P<page>\d+)/$',
        views.list_user_favorites, name='list_user_favorites'),
    url('^~(?P<username>[^/]+)/folders/', include(folder_patterns)),
]

usermgmt/urls.py
from django.conf.urls import (
    include,
    url,
)

from . import (
    group_views,
    views,
)

app_name = 'usermgmt'
group_urls = [
    url('^$', group_views.list_groups, name='list_groups'),
    url('^create/$', group_views.create_group, name='create_group'),
    url('^(?P<group_id>\d+)/$', group_views.view_group, name='view_group'),
    url('^(?P<group_id>\d+)/edit/$', group_views.edit_group,
        name='edit_group'),
    url('^(?P<group_id>\d+)/delete/$', group_views.delete_group,
        name='delete_group'),
]
urlpatterns = [
    url('^register/$', views.Register.as_view(), name='register'),
    url('^accounts/profile/$', views.update_profile, name='update_profile'),
    url('^~([^/]+)/$', views.view_profile, name='view_profile'),
    url('^~(?P<username>[^/]+)/groups/', include(group_urls)),
]

social/models.py
from __future__ import unicode_literals
import markdown

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import (
    GenericForeignKey,
    GenericRelation,
)
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.html import strip_tags

from administration.models import Flag
from honeycomb_markdown import HoneycombMarkdown
from submissions.models import Submission


class Comment(models.Model):
    """A comment posted on a page on the site.

    Comments may be posted on pages for:

    - :model:`submissions.Submission`
    - :model:`promotions.Event`
    - :model:`publishers.Publisher`
    """
    # Related users
    owner = models.ForeignKey(User)
    target_object_owner = models.ForeignKey(
        User, blank=True, null=True, related_name='comments_by_others')

    # Related object (submission, publisher page)
    parent = models.ForeignKey('Comment', blank=True, null=True,
                               related_name='children')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    object_model = GenericForeignKey('content_type', 'object_id')

    # Comment body
    ctime = models.DateTimeField(auto_now_add=True)
    body_raw = models.TextField(verbose_name='Comment')
    body_rendered = models.TextField()
    deleted = models.BooleanField(default=False)
    deleted_by_object_owner = models.BooleanField(default=False)

    flags = GenericRelation(Flag)

    def save(self, *args, **kwargs):
        self.body_rendered = markdown.markdown(
            strip_tags(self.body_raw),
            extensions=[
                'pymdownx.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.smarty',
                'pymdownx.headeranchor',
                'pymdownx.magiclink',
                'pymdownx.smartsymbols',
                'pymdownx.tilde',
                'pymdownx.mark',
                HoneycombMarkdown(),
            ])
        super(Comment, self).save(*args, **kwargs)

    def __str__(self):
        return "{}'s comment on {}".format(
            self.owner.profile.get_display_name(),
            str(self.object_model))

    def __unicode__(self):
        return "{}'s comment on {}".format(
            self.owner.profile.get_display_name(),
            str(self.object_model))

    def get_active_flag(self):
        """Retrieve flag if there is an active flag against this submission"""
        active_flags = self.flags.filter(resolved=None)
        if len(active_flags) > 0:
            return active_flags[0]

    def get_absolute_url(self):
        return '{}#comment-{}'.format(
            self.object_model.get_absolute_url(),
            self.id)


class Rating(models.Model):
    RATING_CHOICES = (
        (1, '1 star'),
        (2, '2 stars'),
        (3, '3 stars'),
        (4, '4 stars'),
        (5, '5 stars'),
    )

    # The user rating the submission
    owner = models.ForeignKey(User)

    # The submission being rated
    submission = models.ForeignKey(Submission)

    # The rating
    rating = models.PositiveIntegerField(choices=RATING_CHOICES)

    def get_stars(self):
        return '&#x2605;' * self.rating + '&#x2606;' * (5 - self.rating)


class EnjoyItem(models.Model):
    # The user enjoying the submission
    owner = models.ForeignKey(User)

    # The submission being enjoyed
    submission = models.ForeignKey(Submission)

    # The date the submission was enjoyed
    ctime = models.DateTimeField(auto_now_add=True)

usermgmt/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User

from .models import (
    FriendGroup,
    Profile,
)


class RegisterForm(UserCreationForm):
    """A form for registering as a new user"""
    email = forms.EmailField(
        label='Email address',
        required=True,
        help_text="""This email will be used as the primary means of
        contacting you, and will not be shared.""",
        widget=forms.EmailInput(attrs={'placeholder': 'user@example.com'}))

    class Meta:
        model = User
        fields = ('username', 'email')
        field_classes = {
            'username': UsernameField,
            'email': forms.EmailField,
        }


class UpdateProfileForm(forms.ModelForm):
    """A form for updating one's profile."""
    class Meta:
        model = Profile
        fields = (
            'can_see_adult_submissions',
            'display_name',
            'profile_raw',
            'results_per_page',
        )


class GroupForm(forms.ModelForm):
    """A form for creating/updating a user group."""
    class Meta:
        model = FriendGroup
        fields = ('name', 'users')

usermgmt/views.py
from django.contrib.auth import (
    authenticate,
    login,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import (
    render,
)
from django.views.generic import FormView

from .forms import (
    RegisterForm,
    UpdateProfileForm,
)
from .models import (
    Profile,
)
from core.templatetags.gravatar import gravatar


class Register(FormView):
    """View to register a new user."""
    template_name = 'registration/new.html'
    form_class = RegisterForm

    def form_valid(self, form):
        form.save()
        new_user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password1'])
        new_profile = Profile(user=new_user)
        new_profile.save()
        login(self.request, new_user)
        return super(Register, self).form_valid(form)

    def get_success_url(self):
        return self.request.POST.get(
            'next', self.request.GET.get('next', reverse('core:front')))

    def get_context_data(self, **kwargs):
        context = super(Register, self).get_context_data(**kwargs)
        context['title'] = 'Register'
        return context


@login_required
def update_profile(request):
    """View to update a user's profile."""
    form = UpdateProfileForm(instance=request.user.profile)

    # Save profile if data was POSTed
    if request.method == 'POST':
        form = UpdateProfileForm(request.POST, instance=request.user.profile)
        form.save()
        messages.success(request, 'Profile updated! View it '
                         '<a href="{}">here</a>!'.format(
                             reverse('usermgmt:view_profile',
                                     args=(request.user.username,))))
    return render(request, 'update_profile.html', {
        'title': 'Update profile',
        'form': form,
        'tab': 'profile',
    })


def view_profile(request, username):
    """View to view a user's profile.

    Args:
        username: the user whose profile to display
    """
    user = User.objects.get(username=username)

    # See if user and reader have any interactions for setting the subtitle
    watched = blocked = blocked_by = False
    if request.user.is_authenticated:
        watched = user in request.user.profile.watched_users.all()
        blocked = user in request.user.profile.blocked_users.all()
        blocked_by = request.user in user.profile.blocked_users.all()
    active_flag = user.profile.get_active_flag()
    subtitle = ''
    display_name = '{} {}'.format(
        gravatar(user.email, size=80),
        user.profile.get_display_name())
    if watched:
        display_name = '&#x2606; {}'.format(display_name)
        subtitle = "following"
    if blocked:
        display_name = '&#x20e0; {}'.format(display_name)
        subtitle = "blocked"
    return render(request, 'view_profile.html', {
        'title': display_name,
        'subtitle': subtitle,
        'author': user,
        'watched': watched,
        'blocked': blocked,
        'blocked_by': blocked_by,
        'active_flag': active_flag,
        'tab': 'profile',
    })

usermgmt/templates/confirm_delete_group.html
{% extends "base.html" %}

{% block content %}
{% include 'profile-tabs-snippet.html' with author=user %}
<div class="alert alert-info">
    <p>You are about to delete your group {{ group.name }}.  Are you sure that you want to do this?</p>
    <form method="post">
        {% csrf_token %}
        <p><button class="btn btn-danger" type="submit"><span class="glyphicon glyphicon-remove"></span> Delete group</button></p>
        <p><a href="{% url 'usermgmt:view_group' username=user.username group_id=group.id %}">No, take me back</a></p>
    </form>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Group members</h2>
        <ul class="list-group">
            {% for member in group.users.all %}
                <li class="list-group-item striped-item group-member">
                    <a href="{% url 'usermgmt:view_profile' user.username %}">{{ member.profile.get_display_name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

usermgmt/templates/list_groups.html
{% extends "base.html" %}

{% block content %}
{% include 'profile-tabs-snippet.html' with author=user %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <ul class="list-group">
            {% for group in groups %}
                <li class="list-group-item striped-item">
                    <a href="{% url 'usermgmt:view_group' username=user.username group_id=group.id %}">{{ group.name }}</a>
                    <div class="pull-right">
                        <a class="btn btn-default" role="button" href="{% url 'usermgmt:edit_group' username=user.username group_id=group.id %}"><span class="glyphicon glyphicon-edit"></span> Edit group</a>
                        <a class="btn btn-danger" role="button" href="{% url 'usermgmt:delete_group' username=user.username group_id=group.id %}"><span class="glyphicon glyphicon-remove"></span> Delete group</a>
                    </div>
                    <div class="clearfix"></div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

usermgmt/templates/profile-tabs-snippet.html
<div class="row profile-tabs">
    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <li role="presentation"{% if tab == 'profile' %} class="active"{% endif %}><a href="{% url 'usermgmt:view_profile' author.username %}">Profile</a></li>
            <li role="presentation"{% if tab == 'submissions' %} class="active"{% endif %}><a href="{% url 'submissions:list_user_submissions' username=author.username %}">Submissions</a></li>
            {% if user == author %}
                <li role="presentation" class="dropdown{% if tab == 'folders' %} active{% endif %}">
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">Folders <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-toggle" href="{% url 'submissions:view_root_level_folders' username=author.username %}"><span class="glyphicon glyphicon-list"></span> List folders</a></li>
                        <li>
                            <a href="{% url 'submissions:create_folder' username=author.username %}">
                                <span class="glyphicon glyphicon-plus"></span> New folder
                            </a>
                        </li>
                        {% if folder %}
                            <li role="divider" class="divider"></li>
                            <li class="dropdown-header">Edit current folder</li>
                            <li>
                                <a href="{% url 'submissions:update_folder' username=author.username folder_id=folder.id folder_slug=folder.slug %}">
                                    <span class="glyphicon glyphicon-edit"></span> Edit folder details
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'submissions:update_submission_order_in_folder' username=author.username folder_id=folder.id folder_slug=folder.slug %}">
                                    <span class="glyphicon glyphicon-sort"></span> Sort submissions
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'submissions:delete_folder' username=author.username folder_id=folder.id folder_slug=folder.slug %}">
                                    <span class="glyphicon glyphicon-remove"></span> Delete folder
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
            {% else %}
                <li role="presentation"{% if tab == 'folders' %} class="active"{% endif %}><a href="{% url 'submissions:view_root_level_folders' username=author.username %}">Folders</a></li>
            {% endif %}
            <li role="presentation"{% if tab == 'favorites' %} class="active"{% endif %}"><a href="{% url 'submissions:list_user_favorites' username=author.username %}">Favorites</a></li>
            {% if user.is_authenticated %}
                {% if user == author %}
                    <li role="presentation" class="dropdown{% if tab == 'social' %} active{% endif %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Social <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'usermgmt:list_groups' username=author.username %}"><span class="glyphicon glyphicon-list"></span> Groups</a></li>
                            {% if group %}
                                <li><a href="{% url 'usermgmt:edit_group' username=author.username group_id=group.id %}"><span class="glyphicon glyphicon-edit"></span> Edit group</a></li>
                                <li><a href="{% url 'usermgmt:delete_group' username=author.username group_id=group.id %}"><span class="glyphicon glyphicon-remove"></span> Delete group</a></li>
                            {% else %}
                                <li><a href="{% url 'usermgmt:create_group' username=author.username %}"><span class="glyphicon glyphicon-plus"></span> Create group</a></li>
                            {% endif %}
                        </ul>
                    </li>
                {% else %}
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Social <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            {% if watched %}
                                <li><a><form action="{% url 'social:unwatch_user' author.username%}" method="post">
                                    {% csrf_token %}
                                    <button class="link-button" type="submit">
                                        Unfollow user
                                    </button>
                                </form></a></li>
                            {% else %}
                                {% if not blocked %}
                                    <li><a><form action="{% url 'social:watch_user' author.username %}" method="post">
                                        {% csrf_token %}
                                        <button class="link-button" type="submit">
                                            Follow user
                                        </button>
                                    </form></a></li>
                                {% endif %}
                            {% endif %}
                            {% if blocked %}
                                <li><a><form action="{% url 'social:unblock_user' author.username %}" method="post">
                                    {% csrf_token %}
                                    <button class="link-button" type="submit">
                                        Unblock user
                                    </button>
                                </form></a></li>
                            {% else %}
                                <li><a><form action="{% url 'social:block_user' author.username %}" method="post">
                                    {% csrf_token %}
                                    <button class="link-button" type="submit">
                                        Block user
                                    </button>
                                </form></a></li>
                                <li><a><form action="{% url 'social:message_user' author.username %}" method="post">
                                    {% csrf_token %}
                                    <button class="link-button" type="submit">
                                        Message user
                                    </button>
                                </form></a></li>
                            {% endif %}
                        </ul>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
    </div>
</div>

usermgmt/templates/update_group.html
{% extends "base.html" %}

{% block content %}
{% include 'profile-tabs-snippet.html' with author=user %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {% include 'registration/form-snippet.html' with form=form %}
        </div>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Save group" </button>
    </div>
</form>
{% endblock %}

usermgmt/templates/view_group.html
{% extends "base.html" %}

{% block content %}
{% include 'profile-tabs-snippet.html' with author=user %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <ul class="list-group">
            <li class="list-group-item list-group-item-info"><a href="{% url 'usermgmt:list_groups' username=user.username %}"><span class="glyphicon glyphicon-menu-left"></span> Back to group listing</a></li>
            {% for member in group.users.all %}
                <li class="list-group-item striped-item group-member">
                    <a href="{% url 'usermgmt:view_profile' user.username %}">{{ member.profile.get_display_name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

usermgmt/templates/view_profile.html
{% extends "base.html" %}
{% load profile_extras %}
{% load flag_extras %}

{% block content %}
{% if blocked_by %}
    <div class="alert alert-warning">You are blocked from viewing this profile by the owner</div>
{% else %}
    {% if not author.is_active %}
        <div class="alert alert-danger">This user's account has been deactivated.</div>
    {% endif %}
    {% include 'profile-tabs-snippet.html' %}
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Profile
                    {% if not active_flag %}
                        <span class="pull-right">
                            <a class="btn btn-warning btn-xs" role="button" href="{% url 'administration:create_flag' %}?content_type=usermgmt:profile&amp;object_id={{ author.profile.id }}">
                                <span class="glyphicon glyphicon-flag"></span>
                                Flag profile for administrative review
                            </a>
                        </span>
                    {% endif %}
                </div>
                <div class="panel-body">
                    {% if active_flag %}
                        <div class="alert alert-danger">
                            <h2>Profile flagged <small>{{ active_flag.subject }}</small></h2>
                            <p>This profile has been flagged by {{ active_flag.flagged_by.profile.get_display_name }} for a {{ active_flag.get_flag_type_display|lower }} violation.</p>
                        {% if user|can_view_flagged_item:active_flag %}
                                {% if user in active_flag.participants.all %}
                                    <p>You are marked as a participant in this flag; only moderators participants in this flag may view this submission.</p>
                                {% else %}
                                    <p>You have permissions to view this submission because of your moderator status; only moderators participants in this flag may view this submission.</p>
                                {% endif %}
                                <p>You may view the flag <a href="{{ active_flag.get_absolute_url }}">here</a></p>
                            </div>
                            {{ author.profile.profile_rendered|safe }}
                        {% else %}
                            </div>
                        {% endif %}
                    {% else %}
                        {{ author.profile.profile_rendered|safe }}
                    {% endif %}
                </div>
                {% comment "Attributes TODO" %}
                <div class="panel-footer">
                    {{ author.profile.attributes|render_attributes }}
                </div>
                {% endcomment %}
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Details
                </div>
                <div class="panel-body">
                    <dl>
                        <dt>Date joined</dt>
                        <dd>{{ author.date_joined|date }}</dd>

                        <dt>Last login</dt>
                        <dd>{{ author.last_login|date }}</dd>

                        <dt>Submissions</dt>
                        <dd>{{ author.submission_set.count }}</dd>

                        <dt>Comments</dt>
                        <dd>{{ author.comment_set.count }}</dd>

                        <dt>Favorites</dt>
                        <dd>{{ author.profile.favorited_submissions.count }}</dd>

                        <dt>Ratings</dt>
                        <dd>{{ author.rating_set.count }}</dd>

                        <dt>Enjoy votes</dt>
                        <dd>{{ author.enjoyitem_set.count }}</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}