api/urls.py
from django.conf.urls import (
    include,
    url,
)


def empty_view(request):
    pass


app_name = 'api'
urlpatterns = [
    url('^$', empty_view, name='root.url'),
    url('^v1/', include('api.v1.urls')),
]

core/urls.py
from django.conf.urls import (
    include,
    url,
)

from .views import (
    flatpage_list,
    front,
    helppage_list,
)

app_name = 'core'
urlpatterns = [
    url('^$', front, name='front'),
    url('^about/$', flatpage_list, name='flatpage_list'),
    url('^about/help/$', helppage_list, name='helppage_list'),
    url('^search/', include('haystack.urls')),
]

honeycomb/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    # Django app urls
    url(r'^_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^_admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # Honeycomb app urls
    url('^', include('administration.urls')),
    url('^', include('usermgmt.urls')),
    url('^', include('social.urls')),
    url('^', include('core.urls')),
    url('^', include('publishers.urls')),
    url('^', include('submissions.urls')),
    url('^', include('tags.urls')),
    url('^activity/', include('activitystream.urls')),
    url('^calls/', include('submitify.urls')),
    url('^api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)

from . import views

app_name = 'social'
user_urls = [
    url('^watch/$', views.watch_user, name='watch_user'),
    url('^unwatch/$', views.unwatch_user, name='unwatch_user'),
    url('^block/$', views.block_user, name='block_user'),
    url('^unblock/$', views.unblock_user, name='unblock_user'),
    url('^message/$', views.message_user, name='message_user'),
]
notification_urls = [
    url('^$', views.view_notifications_ab, name='view_notifications'),
    url('^categories/$', views.view_notifications_categories,
        name='view_notifications_categories'),
    url('^timeline/$', views.view_notifications_timeline,
        name='view_notifications_timeline'),
    url('^timeline/(?P<page>\d+)/$', views.view_notifications_timeline,
        name='view_notifications_timeline'),
    url('^remove/$', views.remove_notifications, name='remove_notifications'),
    url('^nuke/$', views.nuke_notifications, name='nuke_notifications'),
]
submission_urls = [
    url('^favorite/$', views.favorite_submission, name='favorite_submission'),
    url('^unfavorite/$', views.unfavorite_submission,
        name='unfavorite_submission'),
    url('^rate/$', views.rate_submission, name='rate_submission'),
    url('^enjoy/$', views.enjoy_submission, name='enjoy_submission'),
]
comment_urls = [
    url('^post/$', views.post_comment, name='post_comment'),
    url('^delete/$', views.delete_comment, name='delete_comment'),
]

urlpatterns = [
    url('^~([^/]+)/', include(user_urls)),
    url('^notifications/', include(notification_urls)),
    url('^comment/', include(comment_urls)),
    url(settings.SUBMISSION_BASE, include(submission_urls)),
]

submissions/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)

from . import (
    folder_views,
    views,
)

app_name = 'submissions'
full_folder_patterns = [
    url('^$', folder_views.view_folder, name='view_folder'),
    url('^page/(?P<page>\d+)/', folder_views.view_folder, name='view_folder'),
    url('^edit/$', folder_views.update_folder, name='update_folder'),
    url('^delete/$', folder_views.delete_folder, name='delete_folder'),
    url('^reorder/$', folder_views.update_submission_order_in_folder,
        name='update_submission_order_in_folder'),
]
folder_patterns = [
    url('^$', folder_views.view_root_level_folders,
        name='view_root_level_folders'),
    url('^page/(?P<page>\d+)/$', folder_views.view_root_level_folders,
        name='view_root_level_folders'),
    url('^create/$', folder_views.create_folder, name='create_folder'),
    url('^(?P<folder_id>\d+)/$', folder_views.view_folder, name='view_folder'),
    url('^(?P<folder_id>\d+)-(?P<folder_slug>[-\w]+)/',
        include(full_folder_patterns))
]
submission_patterns = [
    url('^$', views.view_submission, name='view_submission'),
    url('^edit/$', views.edit_submission, name='edit_submission'),
    url('^delete/$', views.delete_submission, name='delete_submission'),
]
urlpatterns = [
    url('^submit/$', views.submit, name='submit'),
    url('^(?P<submission_id>\d+)/$', views.view_submission,
        name='view_submission'),
    url(settings.SUBMISSION_BASE, include(submission_patterns)),
    url('^~(?P<username>[^/]+)/submissions/$',
        views.list_user_submissions, name='list_user_submissions'),
    url('^~(?P<username>[^/]+)/submissions/page/(?P<page>\d+)/$',
        views.list_user_submissions, name='list_user_submissions'),
    url('^~(?P<username>[^/]+)/favorites/$',
        views.list_user_favorites, name='list_user_favorites'),
    url('^~(?P<username>[^/]+)/favorites/page/(?P<page>\d+)/$',
        views.list_user_favorites, name='list_user_favorites'),
    url('^~(?P<username>[^/]+)/folders/', include(folder_patterns)),
]

tags/urls.py
from django.conf.urls import (
    include,
    url,
)

from . import views


app_name = 'tags'
tag_views = [
    url('^$', views.view_tag, name='view_tag'),
    url('^(?P<page>\d+)/$', views.view_tag, name='view_tag'),
    url('^favorite/', views.favorite_tag, name='favorite_tag'),
    url('^unfavorite', views.unfavorite_tag, name='unfavorite_tag'),
    url('^block/', views.block_tag, name='block_tag'),
    url('^unblock/', views.unblock_tag, name='unblock_tag'),
]
tags_views = [
    url('^$', views.list_tags, name='list_tags'),
    url('^favorites/$', views.list_submissions_with_favorite_tags,
        name='list_submissions_with_favorite_tags'),
    url('^favorites/(?P<page>\d+)/$',
        views.list_submissions_with_favorite_tags,
        name='list_submissions_with_favorite_tags'),
    url('^tag/(?P<tag_slug>[-\w]+)/', include(tag_views)),
]
categories_views = [
    url('^$', views.list_tags, name='XXX-changeme')
]
urlpatterns = [
    url('^tags/', include(tags_views)),
    url('^categories/', include(categories_views)),
]

usermgmt/urls.py
from django.conf.urls import (
    include,
    url,
)

from . import (
    group_views,
    views,
)

app_name = 'usermgmt'
group_urls = [
    url('^$', group_views.list_groups, name='list_groups'),
    url('^create/$', group_views.create_group, name='create_group'),
    url('^(?P<group_id>\d+)/$', group_views.view_group, name='view_group'),
    url('^(?P<group_id>\d+)/edit/$', group_views.edit_group,
        name='edit_group'),
    url('^(?P<group_id>\d+)/delete/$', group_views.delete_group,
        name='delete_group'),
]
urlpatterns = [
    url('^register/$', views.Register.as_view(), name='register'),
    url('^accounts/profile/$', views.update_profile, name='update_profile'),
    url('^~([^/]+)/$', views.view_profile, name='view_profile'),
    url('^~(?P<username>[^/]+)/groups/', include(group_urls)),
]

submissions/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import (
    EmptyPage,
    Paginator,
)
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.shortcuts import (
    get_object_or_404,
    redirect,
    render,
)
from django.utils import timezone

from .forms import SubmissionForm
from .models import (
    FolderItem,
    Submission,
)
from .utils import (
    filters_for_anonymous_user,
    filters_for_authenticated_user,
)
from activitystream.models import Activity
from administration.models import Flag
from core.templatetags.gravatar import gravatar
from social.forms import CommentForm
from social.models import Comment


def list_user_submissions(request, username=None, page=1):
    """View for listing all of a user's submissions.

    Args:
        username: the user whose submissions to list
        page: the current page for pagination
    """
    reader = request.user
    author = get_object_or_404(User, username=username)

    # Make sure the user can view submissions
    if reader.is_authenticated and reader in \
            author.profile.blocked_users.all():
        return render(request, 'permission_denied.html', {
            'title': 'Permission denied',
        }, status=403)

    # Get a list of submissions based on what the reader can view
    result = author.submission_set.filter(
        filters_for_authenticated_user(reader) if
        reader.is_authenticated else filters_for_anonymous_user())
    paginator = Paginator(result, reader.profile.results_per_page if
                          reader.is_authenticated else 25)
    try:
        submissions = paginator.page(page)
    except EmptyPage:
        submissions = paginator.page(paginator.num_pages)
    display_name = '{} {}'.format(
        gravatar(author.email, size=80),
        author.profile.get_display_name())
    return render(request, 'list_submissions.html', {
        'title': "{}'s submissions".format(display_name),
        'author': author,
        'tab': 'submissions',
        'submissions': submissions,
        'url_prefix': reverse('submissions:list_user_submissions', kwargs={
            'username': author.username,
        })
    })


def list_user_favorites(request, username=None, page=1):
    """View for listing all of a user's favorited submissions.

    Args:
        username: the user whose favorited submissions to list
        page: the current page for pagination
    """
    reader = request.user
    author = get_object_or_404(User, username=username)

    # Make sure the reader can view favorites
    if reader.is_authenticated and reader in \
            author.profile.blocked_users.all():
        return render(request, 'permission_denied.html', {
            'title': 'Permission denied',
        }, status=403)

    # Get a list of submissions based on what the reader can view
    result = author.profile.favorited_submissions.filter(
        filters_for_authenticated_user(reader) if
        reader.is_authenticated else filters_for_anonymous_user())
    paginator = Paginator(result, reader.profile.results_per_page if
                          reader.is_authenticated else 25)
    try:
        submissions = paginator.page(page)
    except EmptyPage:
        submissions = paginator.page(paginator.num_pages)
    display_name = '{} {}'.format(
        gravatar(author.email, size=80),
        author.profile.get_display_name())
    return render(request, 'list_submissions.html', {
        'title': "{}'s favorites".format(display_name),
        'author': author,
        'tab': 'favorites',
        'submissions': submissions,
        'url_prefix': reverse('submissions:list_user_favorites', kwargs={
            'username': author.username,
        })
    })


def view_submission(request, username=None, submission_id=None,
                    submission_slug=None):
    """View for displaying a submission.

    Args:
        username: the owner of the submission
        submission_id: the id of the submission
        submission_slug: the slug of the submission
    """
    # Expand short URLs.
    submission = get_object_or_404(Submission, id=submission_id)
    if username != submission.owner.username or submission_slug != \
            submission.slug:
        return redirect(reverse(
            'submissions:view_submission',
            kwargs={
                'username': submission.owner.username,
                'submission_id': submission.id,
                'submission_slug': submission.slug,
            }))

    # Fetch the submission if allowed
    reader = request.user
    author = submission.owner
    try:
        submission = Submission.objects.get(Q(id=submission_id) & (
            filters_for_authenticated_user(reader, blocked_tags=False) if
            reader.is_authenticated else filters_for_anonymous_user()))
    except Submission.DoesNotExist:
        # XXX Perhaps we should distinguish between 403 and 404 at some point
        return render(request, 'permission_denied.html', {
            'title': 'Permission denied',
        }, status=403)
    active_flag = submission.get_active_flag()

    # Increment the submission views
    if request.user != submission.owner:
        submission.views += 1
        submission.save()
        Activity.create('submission', 'view', submission)
        if active_flag is not None:
            can_view = False
            if request.user in active_flag.participants.all():
                can_view = True
            if not can_view and ((
                    active_flag.flag_type == Flag.SOCIAL and
                    request.user.has_perm(
                        'administration.can_view_social_flags')) or
                    (active_flag.flag_type == Flag.CONTENT and
                     request.user.has_perm(
                         'administration.can_view_content_flags'))):
                can_view = True
            if not can_view:
                return render(request, 'permission_denied.html', {
                    'title': 'Submission flagged',
                    'additional_error': 'This submission is flagged for '
                                        'administrative review.'
                }, status=403)

    display_name = '{} {}'.format(
        gravatar(author.email, size=40),
        author.profile.get_display_name())
    ctype = ContentType.objects.get_for_model(Submission)
    return render(request, 'view_submission.html', {
        'title': submission.title,
        'subtitle': 'by {}'.format(display_name),
        'submission': submission,
        'active_flag': active_flag,
        'comment_form': CommentForm(instance=Comment(
            content_type=ctype,
            object_id=submission.id)),
        'root_level_comments': Comment.objects.filter(
            content_type=ctype,
            object_id=submission.id,
            parent=None)
    })


@login_required
def edit_submission(request, username=None, submission_id=None,
                    submission_slug=None):
    """View for editing an existing submission.

    Args:
        username: the owner of the submission
        submission_id: the id of the submission
        submission_slug: the slug of the submission
    """
    submission = get_object_or_404(Submission, id=submission_id)

    # Make sure the user can edit the submission
    if submission.owner.username != request.user.username:
        messages.error(request, 'You can only edit your own submissions')
        return render(request, 'permission_denied.html', {
            'title': 'Permission denied',
        }, status=403)
    form = SubmissionForm(instance=submission)

    # Save changes if data was POSTed
    if request.method == 'POST':
        form = SubmissionForm(request.POST, request.FILES,
                              instance=submission)

        # Ensure files are below the max size limit
        # NB deployments should also add this to server config
        for f in request.FILES.values():
            if f.size > settings.MAX_UPLOAD_SIZE:
                form.add_error(
                    'content_file', 'Uploads must be less than {}MB'.format(
                        int(settings.MAX_UPLOAD_SIZE / (1024 * 1024))))
        if form.is_valid():
            submission = form.save(commit=False)
            submission.mtime = timezone.now()
            submission.save(update_content=True)

            # Update folder membership: add to folderes
            for folder in form.cleaned_data['folders']:
                if folder.owner == request.user:
                    try:
                        item = FolderItem.objects.get(
                            submission=submission,
                            folder=folder)
                    except FolderItem.DoesNotExist:
                        item = FolderItem(
                            submission=submission,
                            folder=folder,
                            position=len(FolderItem.objects.filter(
                                submission=submission)) + 1)
                        item.save()

            # Update folder membership: remove from folders
            for folder in submission.folders.all():
                if folder not in form.cleaned_data['folders']:
                    item = FolderItem.objects.get(
                        submission=submission,
                        folder=folder)
                    item.delete()

            # Save ManyToMany changes, minus folders, since that uses a through
            # table for managing membership
            form.cleaned_data.pop('folders')
            form.save_m2m()
            messages.success(request, 'Submission updated.')
            return redirect(reverse(
                'submissions:view_submission',
                kwargs={

submissions/templates/comment-body-snippet.html
{% load form_extras %}
{% load gravatar %}
{% load humanize %}
<div class="comment-header">
    <a href="{% url 'usermgmt:view_profile' comment.owner.username %}">{{ comment.owner.email|gravatar }} {{ comment.owner.profile.get_display_name }}</a>
    &bullet; Posted <abbr data-toggle="tooltip" data-placement="bottom" title="{{ comment.ctime|date:'r' }}">{{ comment.ctime|naturaltime }}</abbr>
    &bullet; <a href="#comment-{{ comment.id }}"><span class="glyphicon glyphicon-link"></span> Direct link</a>
    {% if user.is_authenticated and not flag %}
        <span class="pull-right">
            <a class="btn btn-warning btn-xs" role="button" href="{% url 'administration:create_flag' %}?content_type=social:comment&amp;object_id={{ comment.id }}">
                <span class="glyphicon glyphicon-flag"></span>
                Flag for administrative review
            </a>
        </span>
    {% endif %}
    {% if user == comment.owner or user == comment.target_object_owner %}
        <form class="inline pull-right" method="post" action="{% url 'social:delete_comment' %}">
            {% csrf_token %}
            <input type="hidden" name="comment_id" value="{{ comment.id }}" />
            <button type="submit" class="btn btn-danger btn-xs">
                <span class="glyphicon glyphicon-remove"></span>
                Delete comment
            </button>
        </form>
    {% endif %}
</div>
<div class="comment-body">
    {{ comment.body_rendered|safe }}
</div>
{% if can_reply and user.is_authenticated %}
    <div class="comment-reply-form-wrapper">
        <a data-toggle="collapse" href="#reply-{{ comment.id }}" aria-expanded="false" aria-controls="collapseExample">Post reply</a>
        <div id="reply-{{ comment.id }}" class="comment-reply-form collapse">
            <div class="well">
                <form action="{% url 'social:post_comment' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="parent" value="{{ comment.id }}" />
                    {{ comment_form.content_type }}
                    {{ comment_form.object_id }}
                    <div class="form-group">
                        {{ comment_form.body_raw.label }}
                        {{ comment_form.body_raw|append_form_control }}
                    </div>
                    <button class="btn btn-primary" type="submit">Post reply</button>
                </form>
            </div>
        </div>
    </div>
{% endif %}

submissions/templates/confirm_delete_folder.html
{% extends "base.html" %}

{% block content %}
{% include 'profile-tabs-snippet.html' with author=user %}
<div class="alert alert-info">
    <p>You are about to delete your folder {{ folder.name }}.  Are you sure that you want to do this?  All submissions in the folder are safe; this folder will simply be removed from their list of folders.</p>
    <form method="post">
        {% csrf_token %}
        <p><button class="btn btn-danger" type="submit"><span class="glyphicon glyphicon-remove"></span> Delete folder</button></p>
        <p><a href="{% url 'submissions:view_folder' username=user.username folder_id=folder.id folder_slug=folder.slug %}">No, take me back</a></p>
    </form>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Folder contents</h2>
        {% for submission in folder.submissions.all %}
            <div class="row striped-item">
                <div class="col-md-12">
                    {% include 'submission-list-snippet.html' with submission=submission author=submission.owner %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

submissions/templates/confirm_delete_submission.html
{% extends "base.html" %}

{% block content %}
<div class="alert alert-info">
    <p>You are about to delete your submission {{ submission.title }}.  Are you sure that you want to do this?</p>
    <form method="post">
        {% csrf_token %}
        <p><button class="btn btn-danger" type="submit"><span class="glyphicon glyphicon-remove"></span> Delete submission</button></p>
        <p><a href="{% url 'submissions:view_submission' username=user.username submission_id=submission.id submission_slug=submission.slug %}">No, take me back</a></p>
    </form>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Submission description</h2>
        {% if submission.description_rendered %}
            {{ submission.description_rendered|safe }}
        {% else %}
            <em>No description provided</em>
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Submission text</h2>
        <div class="text-block">
            {{ submission.content_rendered|safe }}
        </div>
    </div>
</div>
{% endblock %}

submissions/templates/edit_folder.html
{% extends "base.html" %}

{% block content %}
{% include 'profile-tabs-snippet.html' with author=user %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {% include 'registration/form-snippet.html' with form=form %}
        </div>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> {{ title }}</button>
    </div>
</form>
{% endblock %}

submissions/templates/list_root_folders.html
{% extends "base.html" %}

{% block content %}
{% include 'profile-tabs-snippet.html' with author=user %}
<ul style="list-group">
    {% for folder in folders %}
        <li class="list-group-item striped-item">
            <a href="{% url 'submissions:view_folder' username=owner.username folder_id=folder.id folder_slug=folder.slug %}">{{ folder.name }}</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

submissions/templates/list_submissions.html
{% extends "base.html" %}

{% block content %}
{% include 'profile-tabs-snippet.html' %}
{% if folders or folder %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Folders</h2>
            <ul style="list-group">
                {% if folder %}
                    {% if folder.parent %}
                        <li class="list-group-item list-group-item-info">
                            <a href="{% url 'submissions:view_folder' username=author.username folder_id=folder.parent.id folder_slug=folder.parent.slug %}"><span class="glyphicon glyphicon-menu-left"></span>
                                <em>Parent folder: {{ folder.parent.name }}</em>
                            </a>
                        </li>
                    {% else %}
                        <li class="list-group-item list-group-item-info">
                            <a href="{% url 'submissions:view_root_level_folders' username=author.username %}"><span class="glyphicon glyphicon-menu-left"></span>
                                <em>Parent folder</em>
                            </a>
                        </li>
                    {% endif %}
                {% endif %}
                {% for curr_folder in folders %}
                    <li class="list-group-item striped-item">
                        <a href="{% url 'submissions:view_folder' username=author.username folder_id=curr_folder.id folder_slug=curr_folder.slug %}">
                            <span class="glyphicon glyphicon-folder-open"></span> &nbsp; {{ curr_folder.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <hr />
    {% if not folder %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h2>Submissions not sorted into folders</h2>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h2>Submissions in <em>{{ folder.name }}</em></h2>
            </div>
        </div>
    {% endif %}
{% endif %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <p>
            <em>Showing results {{ submissions.start_index }} through {{ submissions.end_index }} of {{ submissions.paginator.count }}</em>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% for submission in submissions %}
            <div class="row striped-item">
                <div class="col-md-12">
                    {% include 'submission-list-snippet.html' with submission=submission author=author %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% if submissions.has_next or submissions.has_previous %}
    <div class="row">
        <div class="col-md-12 text-center">
            <nav aria-label="Submission pages">
                <ul class="pagination">
                    {% if submissions.has_previous %}
                        <li>
                            <a href="{{ url_prefix }}page/{{ submissions.previous_page_number }}/" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span aria-hidden="true">&laquo;</span></li>
                    {% endif %}
                    {% for page in submissions.paginator.page_range %}
                        {% if submissions.number == page %}
                            <li class="active"><a href="{{ url_prefix }}page/{{ page }}/">{{ page }} <span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li><a href="{{ url_prefix }}page/{{ page }}/">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if submissions.has_next %}
                        <li>
                            <a href="{{ url_prefix }}page/{{ submissions.next_page_number }}/" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><span aria-hidden="true">&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}
{% endblock %}

submissions/templates/subcomments-snippet.html
{% load flag_extras %}
{% for comment in comments %}
    {% with flag=comment.get_active_flag %}
        <div id="comment-{{ comment.id }}">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if comment.deleted %}
                        <em class="text-muted">This comment has been deleted by {% if comment.deleted_by_object_owner %}the page owner{% else %}the commenter{% endif %}.</em>
                    {% elif flag %}
                        {# XXX funky indentation below, reader beware #}
                        {# @makyo 2016-11-11 - if anyone finds a better way, by all means... #}
                        {% if user|can_view_flagged_item:flag %}
                            {% include 'comment-body-snippet.html' %}
                            <div class="alert alert-danger">
                                <p><em>
                                    You can view this comment because you are a moderator or participant in this flag.  Other users cannot view this comment.

                                    You can view the flag <a href="{{ flag.get_absolute_url }}">here</a>.
                                </em></p>
                        {% else %}
                            <div class="alert-danger">
                        {% endif %}
                                <p><em>
                                    This comment has been flagged for administrative review.
                                </em></p>
                            </div>
                        {# XXX end funky indentation #}
                    {% else %}
                        {% include 'comment-body-snippet.html' %}
                    {% endif %}
                </div>
            </div>
            {% if comment.children.count > 0 %}
                <div class="small text-right">
                    <a data-toggle="collapse" href="#replies-{{ comment.id }}" aria-expanded="false" aria-controls="replies-{{ comment.id }}"><span class="glyphicon glyphicon-th-list"></span> Hide replies</a>
                </div>
                <div class="comment-reply">
                    <div class="collapse in" id="replies-{{ comment.id }}">
                        {% include 'subcomments-snippet.html' with comments=comment.children.all can_reply=can_reply %}
                    </div>
                </div>
            {% endif %}
        </div>
    {% endwith %}
{% endfor %}

submissions/templates/submission-list-snippet.html
{% load gravatar %}
<p>
    <a href="{% url 'submissions:view_submission' username=author.username submission_id=submission.id submission_slug=submission.slug %}"><strong>{{ submission.title }}</strong></a> <em>by
    <a href="{% url 'usermgmt:view_profile' author.username %}">{{ author.email|gravatar }}{{ author.profile.get_display_name }}</a></em></p>

{% if submission.description_rendered %}
    <blockquote class="small">
        {{ submission.description_rendered|safe|truncatewords_html:100 }}
    </blockquote>
{% endif %}

<p>
    Views: {{ submission.views }} -
    Rating: <span data-toggle="tooltip" data-placement="bottom" title="{{ submission.rating_average|floatformat }} average out of {{ submission.rating_count }} ratings">{{ submission.rating_stars|safe }}</span> -
    Favorites: {{ submission.favorited_by.count }} -
    {% if submission.can_enjoy %}Submission enjoyed {{ submission.enjoy_votes }} times{% endif %}
</p>
<p>
    Tags:
    {% for tag in submission.tags.all|slice:":10" %}
        <a href="{% url 'tags:view_tag' tag_slug=tag.slug %}">{{ tag }}</a>{% if not forloop.last %}, {% else %}{% if submission.tags.count > 10 %}...{% endif %}{% endif %}
    {% endfor %}
</p>