administration/urls.py
from django.conf.urls import (
    include,
    url,
)

from . import (
    application_views,
    ban_views,
    flag_views,
    views,
)


app_name = 'administration'
application_urls = [
    url('^$', application_views.list_all_applications,
        name='list_all_applications'),
    url('^mine/$', application_views.list_participating_applications,
        name='list_participating_applications'),
    url('^social/$', application_views.list_social_applications,
        name='list_social_applications'),
    url('^content/$', application_views.list_content_applications,
        name='list_content_applications'),
    url('^create/$', application_views.create_application,
        name='create_application'),
    url('^application/(?P<application_id>\d+)/$',
        application_views.view_application,
        name='view_application'),
    url('^application/(?P<application_id>\d+)/claim/$',
        application_views.claim_application, name='claim_application'),
    url('^application/(?P<application_id>\d+)/resolve/$',
        application_views.resolve_application, name='resolve_application'),
]
flag_urls = [
    url('^$', flag_views.list_all_flags, name='list_all_flags'),
    url('^mine/$', flag_views.list_participating_flags,
        name='list_participating_flags'),
    url('^social/$', flag_views.list_social_flags,
        name='list_social_flags'),
    url('^content/$', flag_views.list_content_flags,
        name='list_content_flags'),
    url('^create/$', flag_views.create_flag, name='create_flag'),
    url('^flag/(?P<flag_id>\d+)/$', flag_views.view_flag,
        name='view_flag'),
    url('^flag/(?P<flag_id>\d+)/join/$',
        flag_views.join_flag, name='join_flag'),
    url('^flag/(?P<flag_id>\d+)/resolve/$',
        flag_views.resolve_flag, name='resolve_flag'),
]
ban_urls = [
    url('^$', ban_views.list_bans, name='list_bans'),
    url('^notice/(?P<ban_id>\d+)/(?P<ban_hash>.+)/$', ban_views.ban_notice,
        name='ban_notice'),
    url('^mine/$', ban_views.list_participating_bans,
        name='list_participating_bans'),
    url('^create/$', ban_views.create_ban, name='create_ban'),
    url('^ban/(?P<ban_id>\d+)/$', ban_views.view_ban,
        name='view_ban'),
    url('^ban/(?P<ban_id>\d+)/lift/$', ban_views.lift_ban, name='lift_ban'),
]
admin_urls = [
    url('^$', views.dashboard, name='dashboard'),
    url('^applications/', include(application_urls)),
    url('^flags/', include(flag_urls)),
    url('^bans/', include(ban_urls)),
]
urlpatterns = [
    url('^admin/', include(admin_urls)),
]

api/urls.py
from django.conf.urls import (
    include,
    url,
)


def empty_view(request):
    pass


app_name = 'api'
urlpatterns = [
    url('^$', empty_view, name='root.url'),
    url('^v1/', include('api.v1.urls')),
]

honeycomb/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    # Django app urls
    url(r'^_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^_admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # Honeycomb app urls
    url('^', include('administration.urls')),
    url('^', include('usermgmt.urls')),
    url('^', include('social.urls')),
    url('^', include('core.urls')),
    url('^', include('publishers.urls')),
    url('^', include('submissions.urls')),
    url('^', include('tags.urls')),
    url('^activity/', include('activitystream.urls')),
    url('^calls/', include('submitify.urls')),
    url('^api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usermgmt/urls.py
from django.conf.urls import (
    include,
    url,
)

from . import (
    group_views,
    views,
)

app_name = 'usermgmt'
group_urls = [
    url('^$', group_views.list_groups, name='list_groups'),
    url('^create/$', group_views.create_group, name='create_group'),
    url('^(?P<group_id>\d+)/$', group_views.view_group, name='view_group'),
    url('^(?P<group_id>\d+)/edit/$', group_views.edit_group,
        name='edit_group'),
    url('^(?P<group_id>\d+)/delete/$', group_views.delete_group,
        name='delete_group'),
]
urlpatterns = [
    url('^register/$', views.Register.as_view(), name='register'),
    url('^accounts/profile/$', views.update_profile, name='update_profile'),
    url('^~([^/]+)/$', views.view_profile, name='view_profile'),
    url('^~(?P<username>[^/]+)/groups/', include(group_urls)),
]

administration/models.py
from __future__ import unicode_literals
import hashlib
import markdown

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models

from honeycomb_markdown import HoneycombMarkdown


class Application(models.Model):
    PUBLISHER = 'p'
    CLAIM_PUBLISHER = 'c'
    EVENT = 'e'
    AD = 'a'
    AD_LIFECYCLE = 'l'
    CONTENT_MODERATOR = 'm'
    SOCIAL_MODERATOR = 's'
    # TODO third item in tuple should be next_url for taking the necessary
    # action.
    # @makyo 2016-11-07 #66
    APPLICATION_TYPES = (
        (PUBLISHER, 'Create a publisher page'),
        (CLAIM_PUBLISHER, 'Claim a publisher'),
        (EVENT, 'Schedule an event'),
        (AD, 'Create an ad'),
        (AD_LIFECYCLE, 'Schedule an ad lifecycle'),
        (SOCIAL_MODERATOR, 'Become a social moderator'),
        (CONTENT_MODERATOR, 'Become a content moderator'),
    )
    SOCIAL_TYPES = (
        CLAIM_PUBLISHER,
        CONTENT_MODERATOR,
        SOCIAL_MODERATOR,
    )
    CONTENT_TYPES = (
        PUBLISHER,
        EVENT,
        AD,
        AD_LIFECYCLE,
    )

    ACCEPTED = 'a'
    REJECTED = 'r'
    RESOLUTION_TYPES = (
        (ACCEPTED, 'Accepted'),
        (REJECTED, 'Rejected'),
    )

    applicant = models.ForeignKey(User, related_name='applications')
    admin_contact = models.ForeignKey(
        User, null=True, related_name='applications_responsible_for')

    ctime = models.DateTimeField(auto_now_add=True)
    application_type = models.CharField(max_length=1,
                                        choices=APPLICATION_TYPES)
    body_raw = models.TextField(verbose_name='body')
    body_rendered = models.TextField()
    resolution = models.CharField(max_length=1, blank=True,
                                  choices=RESOLUTION_TYPES)

    def get_absolute_url(self):
        return reverse('administration:view_application', kwargs={
            'application_id': self.id
        })

    def save(self, *args, **kwargs):
        self.body_rendered = markdown.markdown(
            self.body_raw,
            extensions=[
                'pymdownx.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.smarty',
                'pymdownx.headeranchor',
                'pymdownx.magiclink',
                'pymdownx.smartsymbols',
                'pymdownx.tilde',
                'pymdownx.mark',
                HoneycombMarkdown(),
            ])
        super(Application, self).save(*args, **kwargs)

    class Meta:
        ordering = ('resolution', '-ctime')
        permissions = (
            ('can_list_social_applications', 'Can list social applications'),
            ('can_view_social_applications', 'Can view social applications'),
            ('can_resolve_social_applications',
             'Can resolve social applications'),
            ('can_list_content_applications',
             'Can list content applications'),
            ('can_view_content_applications',
             'Can view content applications'),
            ('can_resolve_content_applications',
             'Can resolve content applications'),
            ('can_resolve_applications', 'Can resolve applications'),
        )


class Flag(models.Model):
    """Represents an item flagged for administrative attention."""
    SOCIAL = 's'
    CONTENT = 'c'
    FLAG_TYPES = (
        (SOCIAL, 'Social'),
        (CONTENT, 'Content'),
    )

    # The object being flagged
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    object_model = GenericForeignKey('content_type', 'object_id')
    flagged_object_owner = models.ForeignKey(User, blank=True, null=True,
                                             related_name="flagged_objects")

    # All participants able to take part in a discussion over a flag
    participants = models.ManyToManyField(User, blank=True,
                                          related_name="flags_party_to")

    # The user who flagged the object
    flagged_by = models.ForeignKey(User)

    # Flag information
    flag_type = models.CharField(
        max_length=1, choices=FLAG_TYPES, help_text="""Pick 'content' if the
        issue is with the content of the object, such as a violation of the
        acceptable upload policy.  Pick 'social' if the issue is with the way
        the creator of the content is behaving, such as a violation of the
        terms of service.""")
    ctime = models.DateTimeField(auto_now_add=True)
    resolved = models.DateTimeField(null=True)
    resolved_by = models.ForeignKey(User, related_name='resolved_flags',
                                    null=True)
    resolution = models.TextField(blank=True)
    subject = models.CharField(max_length=100, help_text="""Briefly describe
    the issue with the content or user. (100 characters)""")
    body_raw = models.TextField(verbose_name='body', help_text="""Describe
    the issue with the content or the user.  Be as specific as possible,
    including as many details and as much evidence as you can.  Markdown is
    allowed.""")
    body_rendered = models.TextField()

    def get_absolute_url(self):
        return reverse('administration:view_flag', kwargs={
            'flag_id': self.id,
        })

    def save(self, *args, **kwargs):
        self.body_rendered = markdown.markdown(
            self.body_raw,
            extensions=[
                'pymdownx.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.smarty',
                'pymdownx.headeranchor',
                'pymdownx.magiclink',
                'pymdownx.smartsymbols',
                'pymdownx.tilde',
                'pymdownx.mark',
                HoneycombMarkdown(),
            ])
        super(Flag, self).save(*args, **kwargs)

    def __str__(self):
        return '{} (against {})'.format(self.subject, str(self.object_model))

    def __unicode__(self):
        return '{} (against {})'.format(self.subject, str(self.object_model))

    class Meta:
        ordering = ['-ctime']
        permissions = (
            ('can_list_social_flags', 'Can list social flags'),
            ('can_view_social_flags', 'Can view social flags'),
            ('can_resolve_social_flags', 'Can resolve social flags'),
            ('can_list_content_flags', 'Can list content flags'),
            ('can_view_content_flags', 'Can view content flags'),
            ('can_resolve_content_flags', 'Can resolve content flags'),
            ('can_resolve_flags', 'Can resolve flags'),
        )


class Ban(models.Model):
    """Represents a temporary or permanent ban on a user."""
    # The user being banned
    user = models.ForeignKey(User)

    # The admin who banned the user
    admin_contact = models.ForeignKey(User, related_name='banned_users')

    # The time period of the ban
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateField(blank=True, null=True)
    active = models.BooleanField(default=True)
    user_has_viewed = models.BooleanField(default=False)

    # The reason for the ban
    reason_raw = models.TextField(verbose_name='reason')
    reason_rendered = models.TextField()

    # Any administrative flags if applicable
    flags = models.ManyToManyField(Flag, blank=True,
                                   verbose_name='Pertinent flags')

    def get_absolute_url(self):
        return reverse('administration:view_ban', kwargs={
            'ban_id': self.id,
        })

    def get_ban_hash(self):
        hashtext = '{}:{}'.format(self.id, self.reason_raw)
        return hashlib.sha1(hashtext.encode('utf-8')).hexdigest()

    def save(self, *args, **kwargs):
        self.reason_rendered = markdown.markdown(
            self.reason_raw,
            extensions=[
                'pymdownx.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.smarty',
                'pymdownx.headeranchor',
                'pymdownx.magiclink',
                'pymdownx.smartsymbols',
                'pymdownx.tilde',
                'pymdownx.mark',
                HoneycombMarkdown(),
            ])
        super(Ban, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-start_date',)
        permissions = (
            ('can_ban_users', 'Can ban users'),
            ('can_list_bans', 'Can list bans'),
            ('can_view_bans', 'Can view bans'),
            ('can_lift_bans', 'Can lift bans'),
        )

administration/forms.py
from datetimewidget.widgets import DateWidget
from django import forms

from .models import (
    Application,
    Ban,
    Flag,
)


dateTimeOptions = {
    'format': 'yyyy-mm-dd',
}


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ('application_type', 'body_raw')
        labels = {
            'application_type': 'I would like to...',
        }
        help_texts = {
            'body_raw': "Tell us about what you'd like to do. Markdown okay!",
        }


class BanForm(forms.ModelForm):
    class Meta:
        model = Ban
        fields = ('user', 'end_date', 'reason_raw', 'flags')
        widgets = {
            'end_date': DateWidget(options=dateTimeOptions,
                                   attrs={
                                       'id': 'id_dateTimeField',
                                   },
                                   bootstrap_version=3),
            'user': forms.HiddenInput(),
        }


class FlagForm(forms.ModelForm):
    class Meta:
        model = Flag
        fields = (
            'subject',
            'flag_type',
            'body_raw',
            'content_type',
            'object_id')
        widgets = {
            'content_type': forms.HiddenInput(),
            'object_id': forms.HiddenInput(),
        }

administration/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render

from .models import (
    Application,
    Ban,
    Flag,
)


@login_required
def dashboard(request):
    """View for displaying a dashboard of administrative objects."""
    perms = {
        'administration.can_list_social_applications':
            Application.SOCIAL_TYPES,
        'administration.can_list_content_applications':
            Application.CONTENT_TYPES,
    }

    # Only select unresolve applications
    query = Q(resolution='')

    # Superusers get all applications
    if not request.user.is_superuser:
        # Staff only get applications according to their permissions as well as
        # their own applications
        for perm, allowed_types in perms.items():
            if request.user.has_perm(perm):
                query &= (Q(application_type__in=allowed_types) |
                          Q(applicant=request.user))

        # Non-staff only get their own applications
        if not request.user.is_staff:
            query &= Q(applicant=request.user)
    applications = Application.objects.filter(query)

    # List flags
    perms = {
        'administration.can_list_social_flags':
            Flag.SOCIAL,
        'administration.can_list_content_flags':
            Flag.CONTENT,
    }

    # Only select unresolve flags
    query = Q(resolved=None)

    # Superusers get all flags
    if not request.user.is_superuser:
        # Staff only get flags according to their permissions as well as
        # their own flags
        for perm, allowed_type in perms.items():
            if request.user.has_perm(perm):
                query &= (Q(flag_type=allowed_type) |
                          Q(participants__in=[request.user]))

        # Non-staff only get their own flags
        if not request.user.is_staff:
            query &= Q(participants__in=[request.user])
    flags = Flag.objects.filter(query)

    if request.user.has_perm('administration.can_list_bans'):
        bans = Ban.objects.filter(active=True, end_date__isnull=False)
    else:
        bans = []
    return render(request, 'dashboard.html', {
        'tab': 'dashboard',
        'title': 'Administration Dashboard',
        'applications': applications,
        'flags': flags,
        'bans': bans,
    })

administration/templates/admin-tabs-snippet.html
<div class="row admin-tabs">
    <ul class="nav nav-tabs">
        <li role="presentation"{% if tab == 'dashboard' %} class="active"{% endif %}><a href="{% url 'administration:dashboard' %}">Dashboard</a></li>
        <li role="presentation" class="dropdown{% if tab == 'applications' %} active {% endif %}">
            <a href="{% url 'administration:list_all_applications' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Applications <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="{% url 'administration:create_application' %}">
                        <span class="glyphicon glyphicon-pencil"></span>
                        New application
                    </a>
                </li>
                <li>
                    <a href="{% url 'administration:list_participating_applications' %}">
                        <span class="glyphicon glyphicon-list"></span>
                        My applications
                    </a>
                </li>
                {% if perms.administration.can_list_social_applications and perms.can_list_content_applications %}
                    <li>
                        <a href="{% url 'administration:list_all_applications' %}">
                            <span class="glyphicon glyphicon-list"></span>
                            All applications
                        </a>
                    </li>
                {% endif %}
                {% if perms.administration.can_list_social_applications %}
                    <li>
                        <a href="{% url 'administration:list_social_applications' %}">
                            <span class="glyphicon glyphicon-list"></span>
                            Social applications
                        </a>
                    </li>
                {% endif %}
                {% if perms.administration.can_list_content_applications %}
                    <li>
                        <a href="{% url 'administration:list_content_applications' %}">
                            <span class="glyphicon glyphicon-list"></span>
                            Content applications
                        </a>
                    </li>
                {% endif %}
            </ul>
        </li>
        <li role="presentation" class="dropdown{% if tab == 'flags' %} active {% endif %}">
            <a href="{% url 'administration:list_all_flags' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Flags <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="{% url 'administration:list_participating_flags' %}">
                        <span class="glyphicon glyphicon-list"></span>
                        My flags
                    </a>
                </li>
                {% if perms.administration.can_list_social_flags and perms.can_list_content_flags %}
                    <li>
                        <a href="{% url 'administration:list_all_flags' %}">
                            <span class="glyphicon glyphicon-list"></span>
                            All flags
                        </a>
                    </li>
                {% endif %}
                {% if perms.administration.can_list_social_flags %}
                    <li>
                        <a href="{% url 'administration:list_social_flags' %}">
                            <span class="glyphicon glyphicon-list"></span>
                            Social flags
                        </a>
                    </li>
                {% endif %}
                {% if perms.administration.can_list_content_flags %}
                    <li>
                        <a href="{% url 'administration:list_content_flags' %}">
                            <span class="glyphicon glyphicon-list"></span>
                            Content flags
                        </a>
                    </li>
                {% endif %}
            </ul>
        </li>
        {% if perms.administration.can_list_bans %}
            <li role="presentation" class="dropdown{% if tab == 'bans' %} active {% endif %}">
                <a href="{% url 'administration:list_bans' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Bans <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'administration:list_participating_bans' %}">
                            <span class="glyphicon glyphicon-list"></span>
                            My bans
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'administration:list_bans' %}">
                            <span class="glyphicon glyphicon-list"></span>
                            All bans
                        </a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
</div>

administration/templates/create_application.html
{% extends 'base.html' %}
{% load form_extras %}

{% block content %}
{% include 'admin-tabs-snippet.html' %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.application_type.errors }}
                <label for="id_application_type">{{ form.application_type.label }}</label>
                {{ form.application_type|append_form_control }}
                {% if form.application_type.help_text %}
                    <p class="help-block">{{ form.application_type.help_text|safe }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.body_raw.errors }}
                {{ form.body_raw.label }}
                {{ form.body_raw|append_form_control }}
                {% if form.body_raw.help_text %}
                    <p class="help-block">{{ form.body_raw.help_text|safe }}</p>
                {% endif %}
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit application</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

administration/templates/list_applications.html
{% extends 'base.html' %}

{% block content %}
{% include 'admin-tabs-snippet.html' %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% include 'list-applications-snippet.html' %}
    </div>
</div>
{% endblock %}

administration/templates/view_application.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
{% include 'admin-tabs-snippet.html' %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Application text</h2>
        <div class="text-block">
            {{ application.body_rendered|safe }}
        </div>
        <h2>Information</h2>
        <dl class="dl-horizontal">
            <dt>Created</dt>
            <dd><abbr data-toggle="tooltip" data-placement="bottom" title="{{ application.ctime|date:'r' }}">{{ application.ctime|naturaltime }}</abbr></dd>
            <dt>Application type</dt>
            <dd>{{ application.get_application_type_display }}</dd>
            <dt>Admin contact</dt>
            <dd>
                {% if application.admin_contact %}
                    <a href="{% url 'usermgmt:view_profile' application.admin_contact.username %}">{{ application.admin_contact.profile.get_display_name }}</a>
                    {% if perms.administration.can_resolve_applications and request.user != application.admin_contact %}
                        <form method="post" action="{% url 'administration:claim_application' application_id=application.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-check"></span>
                                Take over
                            </button>
                        </form>
                    {% endif %}
                {% else %}
                    <em>None</em><br />
                    {% if perms.administration.can_resolve_applications %}
                        <form method="post" action="{% url 'administration:claim_application' application_id=application.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-check"></span>
                                Claim
                            </button>
                        </form>
                    {% endif %}
                {% endif %}
            </dd>
            <dt>Resolution</dt>
            <dd>
                {% if application.resolution == 'a' %}
                    <span class="glyphicon glyphicon-ok"></span>
                    Accepted
                {% elif application.resolution == 'r' %}
                    <span class="glyphicon glyphicon-remove"></span>
                    Rejected
                {% else %}
                    <em>No resolution</em><br />
                    {% if user == application.admin_contact %}
                        <form method="post" action="{% url 'administration:resolve_application' application_id=application.id %}" class="form-inline inline">
                            {% csrf_token %}
                            <input type="hidden" name="resolution" value="a" />
                            <button type="submit" class="btn btn-success">
                                <span class="glyphicon glyphicon-ok"></span>
                                Accept
                            </button>
                        </form>
                        <form method="post" action="{% url 'administration:resolve_application' application_id=application.id %}" class="form-inline inline">
                            {% csrf_token %}
                            <input type="hidden" name="resolution" value="r" />
                            <button type="submit" class="btn btn-danger">
                                <span class="glyphicon glyphicon-remove"></span>
                                Reject
                            </button>
                        </form>
                    {% endif %}
                {% endif %}
            </dd>
        </dl>
    </div>
</div>
{% endblock %}

administration/templates/view_flag.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
{% include 'admin-tabs-snippet.html' %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>{{ flag.subject }} <small><a href="{{ flag.object_model.get_absolute_url }}">{{ flag.object_model }}</a></h2>
        <div class="text-block">
            {{ flag.body_rendered|safe }}
        </div>
        <h2>Information</h2>
        <dl class="dl-horizontal">
            <dt>Flag type</dt>
            <dd>{% if flag.flag_type == 's' %}Social{% else %}Content{% endif %}</dd>
            <dt>Created</dt>
            <dd><abbr data-toggle="tooltip" data-placement="bottom" title="{{ flag.ctime|date:'r' }}">{{ flag.ctime|naturaltime }}</abbr></dd>
            <dt>Participants</dt>
            <dd>
                <ul class="list-group">
                    {% for participant in flag.participants.all %}
                        <li class="list-group-item striped-item">
                            {% if participant == flag.flagged_by %}Creator:{% elif participant == flag.flagged_object_owner %}Object owner:{% endif %}
                            <a href="{% url 'usermgmt:view_profile' participant.username %}">{{ participant.profile.get_display_name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </dd>
            <dt>Pertinent ban</dt>
            <dd>
                <ul class="list-group">
                    {% for ban in flag.ban_set.all %}
                        <li class="list-group-item striped-item">
                            <a href="{{ ban.get_absolute_url }}">
                                {{ ban }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </dd>
            {% if perms.administration.can_resolve_flag and not flag.resolved %}
                {% if user in flag.participants.all %}
                    <dt>Resolve flag</dt>
                    <dd>
                        <form action="{% url 'administration:resolve_flag' flag_id=flag.id %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_resolution">Resolution</label>
                                <textarea name="resolution" id="id_resolution" class="form-control" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-success">
                                <span class="glyphicon glyphicon-ok"></span>
                                Resolve flag
                            </button>
                        </form>
                    </dd>
                {% else %}
                    <dt>Join flag</dt>
                    <dd>
                        <form action="{% url 'administration:join_flag' flag_id=flag.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-user"></span>
                                Join flag
                            </button>
                        </form>
                    </dd>
                {% endif %}
            {% endif %}
            {% if perms.administration.can_ban_users %}
                <dt>Escalate to ban</dt>
                <dd>
                    <a href="{% url 'administration:create_ban' %}?user={{ flag.flagged_object_owner.username }}&amp;flag={{ flag.id }}" role="button" class="btn btn-danger">
                        <span class="glyphicon glyphicon-remove"></span>
                        Escalate
                    </a>
                </dd>
            {% endif %}
        </dl>
    </div>
</div>
{% endblock %}